### ISSUE TITLE
Skill Details

### ISSUE THREAD

**Issue by MayomiSGunawardana** [sublimemahesh/support-lanka#17]
Create new class SkillDetails.php

    id: int
    member: foreign key (Member)
    skill: foreign key(Skill)
    description: long-text
    percentage: int
    sort: int

Create Manage Skill Details in Member Dashboard

Add New
Manage All
Update
Delete
Arrange

**Comment by sublimemahesh** [comment]
Still dont complete this?.. now 4 hours ago
